/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CertificateRegistry {
  export type CertStruct = {
    studentName: string;
    ukmName: string;
    eventDate: string;
    isValid: boolean;
  };

  export type CertStructOutput = [
    studentName: string,
    ukmName: string,
    eventDate: string,
    isValid: boolean
  ] & {
    studentName: string;
    ukmName: string;
    eventDate: string;
    isValid: boolean;
  };
}

export interface CertificateRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "admin"
      | "certificates"
      | "getCertificate"
      | "issueCertificate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateIssued"): EventFragment;

  encodeFunctionData(functionFragment: "admin", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [string, string, string, string]
  ): string;

  decodeFunctionResult(functionFragment: "admin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    verificationCode: string,
    studentName: string,
    ukmName: string
  ];
  export type OutputTuple = [
    verificationCode: string,
    studentName: string,
    ukmName: string
  ];
  export interface OutputObject {
    verificationCode: string;
    studentName: string;
    ukmName: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CertificateRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): CertificateRegistry;
  waitForDeployment(): Promise<this>;

  interface: CertificateRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  admin: TypedContractMethod<[], [string], "view">;

  certificates: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean] & {
        studentName: string;
        ukmName: string;
        eventDate: string;
        isValid: boolean;
      }
    ],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [_verificationCode: string],
    [CertificateRegistry.CertStructOutput],
    "view"
  >;

  issueCertificate: TypedContractMethod<
    [
      _verificationCode: string,
      _studentName: string,
      _ukmName: string,
      _eventDate: string
    ],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "admin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, boolean] & {
        studentName: string;
        ukmName: string;
        eventDate: string;
        isValid: boolean;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [_verificationCode: string],
    [CertificateRegistry.CertStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      _verificationCode: string,
      _studentName: string,
      _ukmName: string,
      _eventDate: string
    ],
    [void],
    "nonpayable"
  >;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(string,string,string)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
  };
}
