/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { CertificateRegistry } from "./CertificateRegistry";
export * as factories from "./factories";
export { CertificateRegistry__factory } from "./factories/CertificateRegistry__factory";
